### ISSUE TITLE
Add testanything for Node.js

### ISSUE THREAD

**Issue by augbog** [TestAnything/testanything.github.io#27]
There are a lot of resources now for using TAP with Node.js. Specifically

Tap-producing test hardness for Node -- https://github.com/substack/tape
Nodeschool workshop tutorial in progress -- https://github.com/tomgco/tapeshopper

Would be great to add these resources to the website.

**Comment by jonathanKingston** [comment]
As Node.js is just a flavour of Javascript, the tap producer is listed on the site already at:
http://testanything.org/producers.html

I'm going to suggest a content rewrite to make these pages simpler to find however (Which I think is the actual issue here).

As for the other link, I just clicked on it to get their hello world had a 404 - willing to add when it has progressed a little more perhaps.

**Comment by augbog** [comment]
Ahh apologies I didn't see that page. I was looking at the [Testing with Tap](http://testanything.org/testing-with-tap/) page and noticed it didn't have a section for JavaScript. Not sure if you want to add one for JavaScript/Node.js to that list :)

**Comment by jonathanKingston** [comment]
Not your fault at all @augbog and I think this should be covered in the discussion in #28.

I think adding a plain old JavaScript is enough as we will get people requesting the N other flavours of JavaScript.

Closing in favour of #28 to solve the missing page.
Thanks
