### ISSUE TITLE
404: http://testanything.org/How_TAP_was_named.html

### ISSUE THREAD

**Issue by jonathanKingston** [TestAnything/testanything.github.io#29]
This page appears to now be missing from the site:

http://testanything.org/How_TAP_was_named.html

This is linked from:
http://testanything.org/history.html

**Comment by jonathanKingston** [comment]
I found some missing pages from a broken translated version:

http://translate.google.co.uk/translate?hl=en&sl=pt&u=http://www.univale.com.br/unisite/mundo-j/artigos/47TAP.pdf&prev=search

and

An old reference: https://web.archive.org/web/20100627102611/http://use.perl.org/~petdance/journal/22057

All other referenced seem to have been lost.

**Comment by mblayman** [comment]
It looks like the petdance journal entry contains the AIM chat log where is was named. I think it might be time to remove it because it's not terribly important. It's a bunch of dudes having a private chat and brainstorming such fine ideas as `TAP::That::Ass` and `Testicles And Penis`. :unamused: 

I think the first line in the TAP History page could be reduced to:

> The protocol has been around since 1988.

**Comment by kinow** [comment]
I think we can leave it in Web Archive only, and re-word TAP website as @mblayman suggested.

**Comment by jonathanKingston** [comment]
SGTM
